---
- hosts: default
  become: true
  tasks:
    #- name: upgrade packages
    #  apt: update_cache=yes upgrade=safe
    - name: reconfigure locales
      template: src=locale.gen.j2 dest=/etc/locale.gen owner=root group=root
      notify: re-generate locales
      # correct locales are needed for postgres to install properly.
    - name: uninstall exim4
      apt: name=exim4* state=absent
    - name: install php5
      apt: name=php5-cli state=installed
    - name: install php5-pgsql
      apt: name=php5-pgsql state=installed
    - name: install postgres-9.4
      apt: name=postgresql-9.4 state=installed
    - name: install psycopg2
      apt: name=python-psycopg2 state=installed
    - name: create pg superuser for vagrant
      postgresql_user: name=vagrant role_attr_flags=SUPERUSER
      become_user: postgres
    - name: create pg user for tests
      postgresql_user: name=snake_druid_testing role_attr_flags=CREATEDB password=baa
      become_user: postgres

  handlers:
    - name: re-generate locales
      command: /usr/sbin/locale-gen
